#Micronaut specific
micronaut:
  application:
    name: indexer-web-ui
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: false
  http:
    services:
      grpc-services:
        retry:
          attempts: 5
          delay: 500ms
grpc:
  client:
    plaintext: true
    enable-retry: true
    max-inbound-message-size: 76800000


##application specific
indexer-manager:
  max-history-size: 100

crawls:
  ms-marco:
    indexer: ${indexer.standard}
    type: tsv-crawl
    type-id: msmarco
    vector-config:
      - ${vector-config.title}
      - ${vector-config.body}
    solr-config:
      - ${solr-config.source}
      - ${solr-config.destination}
  solr8-migration:
    type: migration
    vector-fields:
      - ${vector-fields.title}
      - ${vector-fields.body}
    solr-config:
      - ${solr-config.source}
      - ${solr-config.destination}
    indexer: ${indexer.standard}


indexer:
  standard:
    vector-grpc-channel: "localhost:50401"
    chunker-grpc-channel: "localhost:50403"
    source-seed-data:
      enabled: false
      seed-json-file: sample_solr_result.json

solr-config:
  source:
    version: 7.7.3
    collection: source_collection
    connection:
      url: http://localhost:8980/solr
      authentication:
        enabled: false
  destination:
    version: 9.6.1
    collection: destination_collection
    collection_creation:
      collection_config_file: "classpath:default_base_config.zip"
      collection_config_name: semantic_example
      number_of_shards: 1
      number_of_replicas: 2
    connection:
      url: http://localhost:8983/solr
      queue-size: 300 #size of each of the blocking queues  queue-size * thread-count = total document queue before blocking
      thread-count: 3 #number of threads to create for the indexing client queue
      pagination-size: 100 #defaults to 100, optional
      authentication:
        enabled: true
        type: jwt
        client-secret: "gCc8ABmPoHLGCdyiPMbqdPgQnj-yzNN2pJvzXR1rVsWpUQ8cgbZJDKZk-m07Xy2m"
        client-id: "0oaj7tu2ehuix5y6j5d7"
        issuer: https://dev-28615306.okta.com/oauth2/default/v1/token
        issuerAuthId: issuer-auth-id
        subject: your-subject

vector-config:
  title:
    chunk-field: false
    model: mini-LM
    chunk-field-vector-name: title-vector
    similarity-function: cosine #cosine, dot_product, or euclidean.  Defaults to dot_product
    hnsw-max-connections: 16 #if not filled out, this will default to 16
    hnsw-beam-width: 100 #if not filled out, this will default to 100

  body:
    chunk-config:
      enabled: true
      chunk-overlap: 30
      chunk-size: 300
    model: mini-LM
    destination-collection: body-vectors
    chunk-field-vector-name: body-chunk-vector
    similarity-function: cosine #cosine, dot_product, or euclidean.  Defaults to dot_product
    hnsw-max-connections: 16 #if not filled out, this will default to 16
    hnsw-beam-width: 100 #if not filled out, this will default to 100
    collection_creation:
      collection_config_file: "classpath:default-chunk-config.zip"
      collection_config_name: vector_config
      number_of_shards: 1
      number_of_replicas: 2

