micronaut:
  application:
    name: solr-semantic-importer
  http:
    services:
      grpc-services:
        retry:
          attempts: 5
          delay: 500ms
grpc:
  client:
    plaintext: true
    enable-retry: true
